# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Launcher Bug Report
description: Found a bug or issue with the launcher? Sumbit it here!
title: "[BUG]: "
labels: [Bug]
# assignees:
#   - octocat
body:
  - type: textarea
    id: desc
    attributes:
      label: Describe the Bug
      description: "A clear explanation or description of what the bug is"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: "Steps to reproduce the behavior"
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: Expected Behavior
      description: "A clear explanation or description of what you expected to happen"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "A clear explanation or description of what actually happens instead"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
      - Windows
      - Linux
      - macOS
  - type: input
    id: os-distro
    attributes:
      label: Windows Version(eg 11)|Linux Distro(eg Debian)|MacOS Version(eg Ventura)
      placeholder: "Example: Arch/Buster/Bookworm/Rex/etc"
    validations:
      required: false
  - type: input
    id: os-version
    attributes:
      label: Windows Edition(eg Pro)|Linux Version Distro(eg Bookworm)|MacOS Machine(eg M2 Pro)
      placeholder: "Example: Arch/Buster/Bookworm/Rex/etc"
    validations:
      required: false
  - type: input
    id: os-other
    attributes:
      label: Additional OS Details. (Optional)
      placeholder: "Example: Arch/Buster/Bookworm/Rex/etc"
    validations:
      required: false
  - type: input
    id: build
    attributes:
      label: Which version are you running?
      placeholder: "Example: [1.3.2-alpha] python"
    validations:
      required: false
  - type: textarea
    id: logsDumps
    attributes:
      label: "Screenshots"
      description: |
        Screenshots and images to help with the context of the issue.
    validations:
      required: false
