name: Build

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v3
    - name: Install ${{ matrix.os }} dependencies
      if: runner.os == 'Linux'
      run: |
        chmod +x ./Install-Dependencies-for-Mac-and-Linux.sh
        ./Install-Dependencies-for-Mac-and-Linux.sh
