name: Build

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v3
        with:
          repository: qurious-pixel/SMAS_Launcher
          ref: patch-1
    - name: Install ${{ matrix.os }} dependencies
      if: runner.os == 'Linux'
      run: |
        python -m pip install --upgrade pip
        chmod +x ./Install-Dependencies-for-Mac-and-Linux.sh
        ./Install-Dependencies-for-Mac-and-Linux.sh
        chmod +x ./create-exe.sh
        ./create-exe.sh
        ls -al dist/
        
